site_name: Progpoint Manual

theme:
  name: material

nav:
  - Home: index.md
  - Español: es.md
  - English: en.md

markdown_extensions:
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - callouts